CREATE TABLE users (
id BIGSERIAL PRIMARY KEY,
username VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE tasks (
id BIGSERIAL PRIMARY KEY,
user_id BIGINT REFERENCES users(id),
task_title VARCHAR(255) NOT NULL,
description TEXT,
status VARCHAR(50),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
finished_at TIMESTAMP
);