spring.application.name=task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=P@assw0rd!o7
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=3f8a2b1c9d4e7f0a6b5c3d2e1f8a9b7c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a
jwt.expiration=86400000