spring.application.name=task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=P@assw0rd!o7
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
